all: server.suprx client.suprx

server.suprx:
	$(MAKE) -C cl_dll -f Makefile.vita clean
	$(MAKE) -C dlls -f Makefile.vita clean
	$(MAKE) -C dlls -f Makefile.vita

client.suprx:
	$(MAKE) -C cl_dll -f Makefile.vita clean
	$(MAKE) -C dlls -f Makefile.vita clean
	$(MAKE) -C cl_dll -f Makefile.vita

clean:
	$(MAKE) -C cl_dll -f Makefile.vita clean
	$(MAKE) -C dlls -f Makefile.vita clean
